Add touchpoint flag
austinscreations/OXRS-AC-TP32-ESP-FW pull request #5
Opened 2022-07-11 22:57 UTC by austinscreations

added a flag so touchpoint data is only printed on serial in teh debug env - just as a potential security thing if your using keypad

cleaned up a spelling mistake for json schema

and cleaned up teh serial debug so it can look a little nicer. and will get slightly better still switching to the wt32 library that i've turned the wt32 class into. (but i'll do this in a different PR)

2022-07-11 23:04 UTC, sumnerboy12 requested changes

2022-07-11 23:04 UTC, sumnerboy12 commented on src/main.cpp
> +    Serial.println(F("[TP32] starting up..."));
the OXRS standard for these log prefixes is all lowercase

2022-07-11 23:04 UTC, sumnerboy12 commented on src/main.cpp
> +    Serial.print("[TP32] Data x,y ");
Wrap in `F()`

2022-07-11 23:04 UTC, sumnerboy12 commented on src/main.cpp
> +    String LVGL_Arduino = "[TP32] LVGL starting ";
Convert this to 
```
Serial.print(F("[tp32] lvgl starting v"));
Serial.print(lv_version_major());
Serial.print(F("."));
Serial.print(lv_version_minor());
Serial.print(F("."));
Serial.println(lv_version_patch());
```
Try and avoid using `String` wherever possible.

2022-07-11 23:07 UTC, sumnerboy12 commented on src/main.cpp
> +    String LVGL_Arduino = "[TP32] LVGL starting ";
Yeah I know - but if you are changing it, it is a good chance to fix it up properly.

2022-07-11 23:19 UTC, sumnerboy12 approved these changes
Looks good, aside from the one suggestion

2022-07-11 23:19 UTC, sumnerboy12 commented on platformio.ini
> +  -DTOUCHDEBUG
Sorry to be pedantic - might be better to call this `DEBUG_TOUCH` so we can add more `DEBUG_XXX` flags later in a consistent naming scheme?

2022-07-11 23:22 UTC, austinscreations commented on platformio.ini
> +  -DTOUCHDEBUG
sure, couldn't hurt

2022-07-11 23:26 UTC, sumnerboy12 approved these changes

2022-07-12 01:23 UTC, austinscreations commented
redone and merged in #7

2022-07-12 01:23 UTC, closed without merging